### ISSUE TITLE
[urgent] update the documentation

### ISSUE THREAD

**Issue by panavrin** [livecodingyoutube/livecodingyoutube.github.io#13]
createGrid --> create

addGrid--> add

Also please explain how to select videos in multiple ways. 

- one number
- null
- 'all'
- array
- not()
- expression

**Comment by panavrin** [comment]
as some people may approach this website from yesterday, please update the documentation asap

**Comment by bangtoven** [comment]
<img width="384" alt="screen shot 2017-03-19 at 4 13 02 pm" src="https://cloud.githubusercontent.com/assets/966662/24084347/f9ac7742-0cbe-11e7-87b8-1dd31aa2ab4c.png">
<img width="689" alt="screen shot 2017-03-19 at 4 13 10 pm" src="https://cloud.githubusercontent.com/assets/966662/24084352/001aecd0-0cbf-11e7-912a-b0c4f4aae906.png">
