### ISSUE TITLE
function that changes a playspeed

### ISSUE THREAD

**Issue by panavrin** [livecodingyoutube/livecodingyoutube.github.io#3]
a function 

`speed(speed, index) `

change the playsback speed of targetVideo[index] to speed. 

e.g. 
`speed(1.25, 0) // will change the playback speed of the first video to 1.25`

For playback rate refer: player.setPlaybackRate(suggestedRate:Number) in https://developers.google.com/youtube/iframe_api_reference

if index is not specified change the playback speed of all videos.

**Comment by bangtoven** [comment]
speed(1.25) // for all
speed(0.5, 0) // one item
speed(2, 1,2) // multiple items
