### ISSUE TITLE
function - replace video

### ISSUE THREAD

**Issue by panavrin** [livecodingyoutube/livecodingyoutube.github.io#4]
replaceVideo(index list, id) 

replace videos with new youtube id. 

e.g. 

replaceVideo([0,2,4], "FGBhQbmPwH8")

will replace the current video at 0,2, and 4 with the youtube video with the specified id.

**Comment by bangtoven** [comment]
replaceVideo("5y88CkstcWc") // for all
replaceVideo("FGBhQbmPwH8", 1,2)
