### ISSUE TITLE
function for volume controls. 

### ISSUE THREAD

**Issue by panavrin** [livecodingyoutube/livecodingyoutube.github.io#5]
using `player.setVolume(volume:Number):Void`

turnup(volume, list) 

create a function that can turn up and turn down the volume of videos of which index are in the `list`

`turnup(4,[1,2]) // turn up the volume of two videos [1 and 2] by 4 [0,100]`

`turnup(-4,[1,2]) // note that volume can be a negative number.

**Comment by bangtoven** [comment]
mute(true, 2) // mute video 2
mute(false, 2) // unMute
volume(50, 0,1) // set video 0,1's volume to 50
turnup(-20) // turn down 20 for all videos
